import { useState, useEffect } from "react";
import { useParams } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Upload, FileText, CheckCircle, ArrowRight, Send, Loader2 } from "lucide-react";
import { useJobs, Job } from "@/context/JobsContext";
import { useToast } from "@/hooks/use-toast";

type Step = "loading" | "upload" | "questions" | "complete" | "not-found";

// Placeholder questions (will be generated by LLM later)
const placeholderQuestions = [
  "Tell us about your most challenging project and how you overcame the obstacles.",
  "What motivates you to apply for this position?",
  "Describe a situation where you had to work with a difficult team member. How did you handle it?",
  "Where do you see yourself professionally in the next 5 years?",
  "What unique skills or perspectives would you bring to our team?",
];

export default function Apply() {
  const { jobId } = useParams<{ jobId: string }>();
  const { getJob, addCandidate, incrementVisitors } = useJobs();
  const { toast } = useToast();

  const [step, setStep] = useState<Step>("loading");
  const [job, setJob] = useState<Job | null>(null);
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [cvFile, setCvFile] = useState<File | null>(null);
  const [motivationFile, setMotivationFile] = useState<File | null>(null);
  const [answers, setAnswers] = useState<string[]>(Array(5).fill(""));
  const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => {
    const loadJob = async () => {
      if (!jobId) {
        setStep("not-found");
        return;
      }

      try {
        const fetchedJob = await getJob(jobId);
        if (fetchedJob) {
          setJob(fetchedJob);
          setStep("upload");
          // Increment visitors after job is found
          incrementVisitors(jobId);
        } else {
          setStep("not-found");
        }
      } catch (error) {
        console.error("Failed to load job:", error);
        setStep("not-found");
      }
    };

    loadJob();
  }, [jobId, getJob, incrementVisitors]);

  if (step === "loading") {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <Loader2 className="h-8 w-8 animate-spin mx-auto text-primary" />
          <p className="mt-4 text-muted-foreground">Loading job details...</p>
        </div>
      </div>
    );
  }

  if (step === "not-found" || !job) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-2xl font-bold">Job Not Found</h1>
          <p className="mt-2 text-muted-foreground">
            This job posting doesn't exist or has been removed.
          </p>
        </div>
      </div>
    );
  }

  const handleFileChange = (
    e: React.ChangeEvent<HTMLInputElement>,
    type: "cv" | "motivation"
  ) => {
    const file = e.target.files?.[0];
    if (file && file.type === "application/pdf") {
      if (type === "cv") {
        setCvFile(file);
      } else {
        setMotivationFile(file);
      }
    } else {
      toast({
        title: "Invalid file type",
        description: "Please upload a PDF file.",
        variant: "destructive",
      });
    }
  };

  const handleUploadSubmit = () => {
    if (!firstName.trim() || !lastName.trim()) {
      toast({
        title: "Missing information",
        description: "Please enter your first and last name.",
        variant: "destructive",
      });
      return;
    }
    if (!cvFile || !motivationFile) {
      toast({
        title: "Missing files",
        description: "Please upload both your CV and motivation letter.",
        variant: "destructive",
      });
      return;
    }
    setStep("questions");
  };

  const handleAnswerChange = (index: number, value: string) => {
    const newAnswers = [...answers];
    newAnswers[index] = value;
    setAnswers(newAnswers);
  };

  const handleQuestionsSubmit = async () => {
    const unanswered = answers.some((a) => !a.trim());
    if (unanswered) {
      toast({
        title: "Incomplete responses",
        description: "Please answer all questions before submitting.",
        variant: "destructive",
      });
      return;
    }

    setIsSubmitting(true);

    try {
      // Add candidate to the job
      await addCandidate(jobId!, {
        firstName,
        lastName,
        cvFileName: cvFile!.name,
        cvUrl: URL.createObjectURL(cvFile!),
        motivationFileName: motivationFile!.name,
        motivationUrl: URL.createObjectURL(motivationFile!),
      });

      setStep("complete");
    } catch (error) {
      console.error("Failed to submit application:", error);
      toast({
        title: "Submission failed",
        description: "Please try again later.",
        variant: "destructive",
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen py-12 sm:py-16 bg-gradient-to-br from-primary/5 via-background to-accent/5">
      <div className="container-page max-w-2xl">
        {/* Job Header */}
        <div className="text-center mb-8">
          <h1 className="text-2xl font-bold sm:text-3xl">{job.title}</h1>
          <p className="mt-2 text-muted-foreground">
            {job.company} • {job.location}
          </p>
        </div>

        {/* Progress Indicator */}
        <div className="flex items-center justify-center mb-8">
          <div className="flex items-center gap-2">
            <div
              className={`flex h-8 w-8 items-center justify-center rounded-full text-sm font-semibold ${
                step === "upload"
                  ? "bg-primary text-primary-foreground"
                  : "bg-primary/20 text-primary"
              }`}
            >
              1
            </div>
            <div className="h-1 w-8 rounded bg-muted" />
            <div
              className={`flex h-8 w-8 items-center justify-center rounded-full text-sm font-semibold ${
                step === "questions"
                  ? "bg-primary text-primary-foreground"
                  : step === "complete"
                  ? "bg-primary/20 text-primary"
                  : "bg-muted text-muted-foreground"
              }`}
            >
              2
            </div>
            <div className="h-1 w-8 rounded bg-muted" />
            <div
              className={`flex h-8 w-8 items-center justify-center rounded-full text-sm font-semibold ${
                step === "complete"
                  ? "bg-success text-success-foreground"
                  : "bg-muted text-muted-foreground"
              }`}
            >
              ✓
            </div>
          </div>
        </div>

        {/* Step 1: Upload Documents */}
        {step === "upload" && (
          <div className="card-elevated p-6 sm:p-8">
            <h2 className="text-xl font-semibold mb-6">Upload Your Documents</h2>

            {/* Name Fields */}
            <div className="grid gap-4 sm:grid-cols-2 mb-6">
              <div>
                <Label htmlFor="firstName">First Name</Label>
                <Input
                  id="firstName"
                  value={firstName}
                  onChange={(e) => setFirstName(e.target.value)}
                  placeholder="Enter your first name"
                  className="mt-1.5"
                />
              </div>
              <div>
                <Label htmlFor="lastName">Last Name</Label>
                <Input
                  id="lastName"
                  value={lastName}
                  onChange={(e) => setLastName(e.target.value)}
                  placeholder="Enter your last name"
                  className="mt-1.5"
                />
              </div>
            </div>

            {/* CV Upload */}
            <div className="mb-6">
              <Label>CV / Resume (PDF)</Label>
              <div className="mt-1.5">
                <label className="flex flex-col items-center justify-center w-full h-32 border-2 border-dashed rounded-xl cursor-pointer hover:bg-muted/50 transition-colors">
                  <div className="flex flex-col items-center justify-center pt-5 pb-6">
                    {cvFile ? (
                      <>
                        <FileText className="h-8 w-8 text-primary mb-2" />
                        <p className="text-sm font-medium">{cvFile.name}</p>
                      </>
                    ) : (
                      <>
                        <Upload className="h-8 w-8 text-muted-foreground mb-2" />
                        <p className="text-sm text-muted-foreground">
                          Click to upload your CV
                        </p>
                      </>
                    )}
                  </div>
                  <input
                    type="file"
                    accept=".pdf"
                    className="hidden"
                    onChange={(e) => handleFileChange(e, "cv")}
                  />
                </label>
              </div>
            </div>

            {/* Motivation Letter Upload */}
            <div className="mb-8">
              <Label>Motivation Letter (PDF)</Label>
              <div className="mt-1.5">
                <label className="flex flex-col items-center justify-center w-full h-32 border-2 border-dashed rounded-xl cursor-pointer hover:bg-muted/50 transition-colors">
                  <div className="flex flex-col items-center justify-center pt-5 pb-6">
                    {motivationFile ? (
                      <>
                        <FileText className="h-8 w-8 text-primary mb-2" />
                        <p className="text-sm font-medium">
                          {motivationFile.name}
                        </p>
                      </>
                    ) : (
                      <>
                        <Upload className="h-8 w-8 text-muted-foreground mb-2" />
                        <p className="text-sm text-muted-foreground">
                          Click to upload your motivation letter
                        </p>
                      </>
                    )}
                  </div>
                  <input
                    type="file"
                    accept=".pdf"
                    className="hidden"
                    onChange={(e) => handleFileChange(e, "motivation")}
                  />
                </label>
              </div>
            </div>

            <Button
              variant="gradient"
              size="xl"
              className="w-full"
              onClick={handleUploadSubmit}
            >
              Continue to Questions
              <ArrowRight className="ml-2 h-5 w-5" />
            </Button>
          </div>
        )}

        {/* Step 2: Answer Questions */}
        {step === "questions" && (
          <div className="card-elevated p-6 sm:p-8">
            <h2 className="text-xl font-semibold mb-2">Interview Questions</h2>
            <p className="text-sm text-muted-foreground mb-6">
              Please answer the following questions thoughtfully.
            </p>

            <div className="space-y-6">
              {placeholderQuestions.map((question, index) => (
                <div key={index}>
                  <Label className="text-base">
                    {index + 1}. {question}
                  </Label>
                  <Textarea
                    value={answers[index]}
                    onChange={(e) => handleAnswerChange(index, e.target.value)}
                    placeholder="Type your answer here..."
                    className="mt-2 min-h-[100px]"
                  />
                </div>
              ))}
            </div>

            <Button
              variant="gradient"
              size="xl"
              className="w-full mt-8"
              onClick={handleQuestionsSubmit}
              disabled={isSubmitting}
            >
              {isSubmitting ? (
                <>
                  <div className="mr-2 h-5 w-5 animate-spin rounded-full border-2 border-current border-t-transparent" />
                  Submitting...
                </>
              ) : (
                <>
                  Submit Application
                  <Send className="ml-2 h-5 w-5" />
                </>
              )}
            </Button>
          </div>
        )}

        {/* Step 3: Complete */}
        {step === "complete" && (
          <div className="card-elevated p-6 sm:p-8 text-center">
            <div className="flex justify-center mb-6">
              <div className="flex h-20 w-20 items-center justify-center rounded-full bg-success/10">
                <CheckCircle className="h-10 w-10 text-success" />
              </div>
            </div>
            <h2 className="text-2xl font-bold mb-2">Thank You!</h2>
            <p className="text-muted-foreground mb-6">
              Your application has been successfully submitted. We appreciate you
              taking the time to complete the interview process.
            </p>
            <p className="text-sm text-muted-foreground">
              The hiring team will review your application and get back to you
              soon.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
